services:
  db:
    image: postgres:16
    container_name: habits
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: habits
    volumes:
      # This volume persists data on your host machine
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres-data:
